name = "dblens"
compatibility_date = "2024-11-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "../../web/out"

[env.preview.vars]
NEXT_PUBLIC_API_HOST = "https://airdrops.dblens.burnt.zone"

[env.production.vars]
NEXT_PUBLIC_API_HOST = "https://airdrops.dblens.burnt.zone"
