name = "mainnet-airdrop-dblens"
compatibility_date = "2024-11-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "../../web/out"

services = [
  { binding = "api", service = "dblens-api" }
]
